version: '3.8'

services:
  web:
    build: .
    container_name: api_yatube
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db
    networks:
      - backend
    user: appuser

  db:
    image: postgres:13-alpine
    container_name: yatube_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]

volumes:
  static_volume:
  db_data:

networks:
  backend:
    driver: bridge